=== GustavoElMaximo/SJSX/samples/myTest/XSD_and_XML_Source/MyXML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2007 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="xml">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="codigoCliente"/>
				<xs:element ref="codigoAgencia"/>
				<xs:element ref="datosAgencia"/>
				<xs:element ref="productos"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="via">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="telefono">
		<xs:simpleType>
			<xs:restriction base="xs:int" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="poblacion">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="piso">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="numero">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="nombre">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="productos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="producto" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="producto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="codigo"/>
				<xs:element ref="cantidad"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="email">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="direccion">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="datosAgencia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre"/>
				<xs:element ref="direccion"/>
				<xs:element ref="via"/>
				<xs:element ref="numero"/>
				<xs:element ref="piso"/>
				<xs:element ref="telefono"/>
				<xs:element ref="poblacion"/>
				<xs:element ref="cp"/>
				<xs:element ref="categoriaAgencia"/>
				<xs:element ref="email"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="cp">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="codigoCliente">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="codigoAgencia">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="codigo">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="categoriaAgencia">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="cantidad">
		<xs:simpleType>
			<xs:restriction base="xs:integer" />
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== GustavoElMaximo/SJSX/samples/myTest/XSD_and_XML_Source/MyXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<xml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="MyXML.xsd">
	<codigoCliente>00001</codigoCliente>
	<codigoAgencia>3424241234</codigoAgencia>
	<datosAgencia>
		<nombre>V. FORMACION</nombre>
		<direccion>AG.FICTICIA FORMACION</direccion>
		<via>CL</via>
		<numero>S/N</numero>
		<piso/>
		<telefono>166666666</telefono>
		<poblacion>PALMA DE MALLORCA</poblacion>
		<cp>07000</cp>
		<categoriaAgencia>A</categoriaAgencia>
		<email>yo@sjsx.com</email>
	</datosAgencia>
	<productos>
		<producto>
			<codigo>EWQR</codigo>
			<cantidad>0020</cantidad>
		</producto>
		<producto>
			<codigo>EWQRE</codigo>
			<cantidad>0010</cantidad>
		</producto>
		<producto>
			<codigo>MECSL$</codigo>
			<cantidad>0001</cantidad>
		</producto>
	</productos>
</xml>
